### PR TITLE
Add Dutch language

### PR DESCRIPTION
**Pull request by toineenzo**
Added nl.yml and translated to Dutch
Fixed small typo in en.yml

### CODE REVIEW

**Comment by toineenzo** [comment]
ANother small thing: could you add an explanation to the Readme about the ampersands? (&)
Is this for linking shortkeys? I'm not sure

**Comment by m417z** [comment]
Hi, thank you for the translation!

> could you add an explanation to the Readme about the ampersands in the strings? (&)

Added, let me know if it's clear enough.

And let me know when the translation ready to be merged.

**Comment by toineenzo** [comment]
> Hi, thank you for the translation!
> 
> > could you add an explanation to the Readme about the ampersands in the strings? (&)
> 
> Added, let me know if it's clear enough.
> 
> And let me know when the translation ready to be merged.

Thanks! Everything looks good, so you can merge it

**Comment by m417z** [comment]
Thank you! The translation will be available in the next version of Windhawk.

**Pull request merged**
