### PR TITLE
Update jp.yml

### PR DESCRIPTION
**Pull request by Keitan924111**
Translation of untranslated portions and proofreading of some translated portions.

### CODE REVIEW

**Comment by Keitan924111** [comment]
Is this part OK?
For the time being, what I want to do is to make it feel like "(**O**)Windhawkを開く" ...

**Comment by m417z** [comment]
Are you asking how this dialog looks translated?

image

With the Alt key held:

image

P.S. There was a small problem since the file was called `jp.yml` while it should be `ja.yml`. I just pushed a fix for it.

**Comment by Keitan924111** [comment]
Oh, yes! I'm glad I was right about what I thought I was doing. Thanks for the verification.
As for the file name, I am not sure. Sorry if I did something extra.

**Comment by m417z** [comment]
@Keitan924111 did you notice that some texts are still untranslated? Specifically:
`TRAY_TOOLKIT`, `alert`, `offButton`, `offConfirm`, `offConfirmOk`, `offConfirmCancel`.
You can search for `~` in the file to quickly find the missing translations.

**Comment by Keitan924111** [comment]
Oops, I didn't realize it was still there. I didn't notice. I will get to it as soon as I can.

**Pull request merged**
